import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

const geistSans = localFont({
  src: [
    {
      path: "../fonts/Universal-Sans-Display-350.ttf",
      weight: "350",
    },
    {
      path: "../fonts/Universal-Sans-Display-400.ttf",
      weight: "400",
    },
    {
      path: "../fonts/Universal-Sans-Display-450.ttf",
      weight: "450",
    },
    {
      path: "../fonts/Universal-Sans-Display-500.ttf",
      weight: "500",
    },
  ],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        scrollBehavior: "smooth",
      }}
    >
      <body className={`${geistSans.className} antialiased`}>{children}</body>
    </html>
  );
}
