import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import "./home.css";
import Script from "next/script";

const geistSans = localFont({
  src: [
    {
      path: "../fonts/Universal-Sans-Display-350.ttf",
      weight: "350",
    },
    {
      path: "../fonts/Universal-Sans-Display-400.ttf",
      weight: "400",
    },
    {
      path: "../fonts/Universal-Sans-Display-450.ttf",
      weight: "450",
    },
    {
      path: "../fonts/Universal-Sans-Display-500.ttf",
      weight: "500",
    },
  ],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        scrollBehavior: "smooth",
        scrollPaddingTop: "56px",
      }}
    >
      <body className={`${geistSans.className} antialiased`}>
        {children}

        {/* Chatbot Script */}
        <Script
          id="chatbot-script"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `
              window.__ow = window.__ow || {};
              window.__ow.organizationId = "da59421c-7f39-4052-88cf-7b7eebfdc8cd";
              window.__ow.template_id = "ebae263a-5f08-4dcf-b3aa-2923c3288c71";
              window.__ow.integration_name = "manual_settings";
              window.__ow.product_name = "chatbot";   
              (function(n,t,c){
                function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}
                var e={_q:[],_h:null,_v:"2.0",on:function(){i(["on",c.call(arguments)])},
                once:function(){i(["once",c.call(arguments)])},off:function(){i(["off",c.call(arguments)])},
                get:function(){if(!e._h)throw new Error("[OpenWidget] You can't use getters before load.");
                return i(["get",c.call(arguments)])},call:function(){i(["call",c.call(arguments)])},
                init:function(){
                  var n=t.createElement("script");
                  n.async=!0,n.type="text/javascript",
                  n.src="https://cdn.openwidget.com/openwidget.js",
                  t.head.appendChild(n)
                }};
                !n.__ow.asyncInit&&e.init(),n.OpenWidget=n.OpenWidget||e
              }(window,document,[].slice));
            `,
          }}
        />

        {/* NoScript Fallback */}
        <noscript>
          You need to{" "}
          <a
            href="https://www.chatbot.com/help/chat-widget/enable-javascript-in-your-browser/"
            rel="noopener nofollow"
          >
            enable JavaScript
          </a>
          in order to use the AI chatbot tool powered by
          <a
            href="https://www.chatbot.com/"
            rel="noopener nofollow"
            target="_blank"
          >
            ChatBot
          </a>
          .
        </noscript>
      </body>
    </html>
  );
}
